name: Terraform module for Security Groups
on:
  push: {}

jobs:
  build:
    name: Continuous Integration for Security Groups Module
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    steps:

      - name: Checkout Git Code for Security Groups
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.4
          terraform_wrapper: false

      - name: Terraform Lint
        run: terraform fmt --diff --check --recursive
        
      - name: Terraform Validate
        run: terraform init; terraform validate

      - name: Terraform TfSec
        run: |
          wget https://github.com/tfsec/tfsec/releases/download/v0.36.7/tfsec-linux-amd64
          mv tfsec-linux-amd64 tfsec
          chmod +x tfsec
          ./tfsec -s .
      - name: Setup Go
        uses: actions/setup-go@v3
        with: 
          go-version: 1.18.3
      
      - name: Run build
        run: go mod init test

      - name: Unit Test with Terratest
        working-directory: /home/runner/work/sikv3-aws-security-groups/test
        run: go test -v -timeout 10m
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-east-1'
